const $ = s => document.querySelector(s);
const sites = [{name:'New York HQ',region:'Americas',clients:1245,score:96,devices:84,status:'Excellent'},{name:'London Office',region:'EMEA',clients:892,score:82,devices:46,status:'Fair'},{name:'Singapore DC',region:'APAC',clients:1078,score:91,devices:62,status:'Excellent'},{name:'Austin Studio',region:'Americas',clients:348,score:95,devices:21,status:'Excellent'},{name:'Berlin Office',region:'EMEA',clients:271,score:89,devices:19,status:'Excellent'}];
const devices = [{name:'nyc-ap-042',type:'Access Point',site:'New York HQ',ip:'10.24.8.42',version:'0.14.2960',uptime:'143d',status:'Online'},{name:'lon-sw-003',type:'Switch',site:'London Office',ip:'10.31.2.13',version:'0.14.2960',uptime:'89d',status:'Online'},{name:'sgp-srx-01',type:'Gateway',site:'Singapore DC',ip:'10.48.0.1',version:'0.14.2960',uptime:'203d',status:'Warning'},{name:'nyc-sw-021',type:'Switch',site:'New York HQ',ip:'10.24.3.21',version:'0.14.2960',uptime:'54d',status:'Online'},{name:'lon-ap-011',type:'Access Point',site:'London Office',ip:'10.31.8.11',version:'0.14.2960',uptime:'77d',status:'Online'}];
const endpoints = [{name:'nadia-mbp',type:'Wi-Fi',site:'New York HQ',ip:'10.24.18.44',signal:'-49 dBm',score:98,last:'Now'},{name:'conf-room-4',type:'Wired',site:'London Office',ip:'10.31.4.88',signal:'1 Gbps',score:89,last:'Now'},{name:'warehouse-scanner-03',type:'Wi-Fi',site:'Singapore DC',ip:'10.48.19.32',signal:'-64 dBm',score:84,last:'1m ago'},{name:'design-imac-02',type:'Wired',site:'Austin Studio',ip:'10.29.3.72',signal:'1 Gbps',score:96,last:'Now'}];
let alerts = [{level:'critical',title:'Roaming failures at London Office',detail:'27 clients affected in the last hour',site:'London Office',time:'8m ago',recommendation:'Review AP channel utilization and enable band steering on 6 affected access points.'},{level:'high',title:'WAN latency trending high',detail:'Singapore DC · 42ms above baseline',site:'Singapore DC',time:'22m ago',recommendation:'Fail over real-time traffic to the secondary ISP tunnel until latency returns to baseline.'},{level:'high',title:'Gateway CPU above threshold',detail:'sgp-srx-01 sustained at 84% CPU',site:'Singapore DC',time:'36m ago',recommendation:'Inspect top applications and schedule a capacity review.'},{level:'low',title:'Firmware upgrade available',detail:'18 access points have an approved release',site:'New York HQ',time:'1h ago',recommendation:'Schedule an automated upgrade window.'}];
let totalClients = 4892;
function badge(status){return `<span class="state ${status.toLowerCase()}">${status}</span>`}
function renderSites(){const q=$('#site-search')?.value.toLowerCase()||'', f=$('#site-filter')?.value||'all'; $('#sites-table').innerHTML=sites.filter(x=>x.name.toLowerCase().includes(q)&&(f==='all'||x.status===f)).map(x=>`<tr><td><b>${x.name}</b></td><td>${x.region}</td><td>${x.clients.toLocaleString()}</td><td><b>${x.score}</b>/100</td><td>${x.devices}</td><td>${badge(x.status)}</td><td><button class="row-action site-drill" data-site="${x.name}">View</button></td></tr>`).join('')}
function renderDevices(){const q=$('#device-search')?.value.toLowerCase()||'',f=$('#device-filter')?.value||'all'; $('#devices-table').innerHTML=devices.filter(x=>(x.name+x.site+x.ip).toLowerCase().includes(q)&&(f==='all'||x.type===f)).map(x=>`<tr><td><b>${x.name}</b></td><td>${x.type}</td><td>${x.site}</td><td class="mono">${x.ip}</td><td>${x.version}</td><td>${x.uptime}</td><td>${badge(x.status)}</td></tr>`).join('')}
function renderClients(){const q=$('#client-search')?.value.toLowerCase()||'',f=$('#client-filter')?.value||'all'; $('#clients-table').innerHTML=endpoints.filter(x=>(x.name+x.ip).toLowerCase().includes(q)&&(f==='all'||x.type===f)).map(x=>`<tr><td><b>${x.name}</b></td><td>${x.type}</td><td>${x.site}</td><td class="mono">${x.ip}</td><td>${x.signal}</td><td><b>${x.score}</b>/100</td><td>${x.last}</td></tr>`).join('')}
function renderOverview(){ $('#site-list').innerHTML=sites.slice(0,3).map((s,i)=>`<div><span class="site-icon ${i===1?'purple':i===2?'blue-bg':''}">${s.name.slice(0,2).toUpperCase()}</span><p><b>${s.name}</b><small>${s.clients.toLocaleString()} clients</small></p><strong>${s.score}</strong><span class="${s.status==='Fair'?'warn-label':'good-label'}">${s.status}</span></div>`).join(''); $('#events').innerHTML=['High latency detected|WAN · Singapore DC|orange|Investigating','Access point adopted|Wi-Fi · New York HQ|green|Complete','Firmware upgrade scheduled|Switches · London Office|blue|Tonight, 02:00'].map((x,i)=>{let[t,d,c,s]=x.split('|');return `<div><time>${['09:42','09:18','08:57'][i]}</time><span class="event-dot ${c}"></span><p><b>${t}</b><small>${d}</small></p><em class="${c==='green'?'complete':''}">${s}</em></div>`}).join('')}
function renderWan(){ $('#wan-cards').innerHTML=[['Singapore primary','42 ms','Elevated','high'],['Singapore backup','18 ms','Healthy','good'],['London SD-WAN','16 ms','Healthy','good'],['New York MPLS','12 ms','Healthy','good']].map(x=>`<article class="panel wan-card"><p class="eyebrow">${x[0]}</p><strong>${x[1]}</strong><span class="state ${x[3]}">${x[2]}</span><div class="wan-chart"></div><small>Median latency · last 15 minutes</small></article>`).join('')}
function renderAlerts(){ $('#alert-badge').textContent=alerts.length; $('#open-alerts').textContent=String(alerts.length).padStart(2,'0'); $('#alerts-list').innerHTML=alerts.map((a,i)=>`<button class="alert-row ${i===0?'selected':''}" data-alert="${i}"><span class="severity ${a.level==='high'?'high':a.level==='low'?'low':''}"></span><span><b>${a.title}</b><small>${a.detail}</small></span><em>${a.time}</em></button>`).join(''); selectAlert(0)}
function selectAlert(i){const a=alerts[i];if(!a)return; $('#alert-detail').innerHTML=`<p class="eyebrow">${a.level.toUpperCase()} · ${a.site}</p><h2>${a.title}</h2><p>${a.detail}</p><div class="recommendation"><b>✦ Recommended action</b><p>${a.recommendation}</p></div><div class="detail-actions"><button class="secondary" id="snooze">Snooze</button><button class="primary" id="resolve">Mark resolved</button></div>`; $('.alert-row.selected')?.classList.remove('selected'); $(`[data-alert="${i}"]`)?.classList.add('selected'); $('#resolve')?.addEventListener('click',()=>{alerts.splice(i,1);renderAlerts();toast('Alert marked resolved')}); $('#snooze')?.addEventListener('click',()=>toast('Alert snoozed for 4 hours'))}
function navigate(view){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));$(`#${view}-view`).classList.add('active');document.querySelectorAll('#navigation a').forEach(x=>x.classList.toggle('active',x.dataset.view===view));$('#crumb').innerHTML=`${view[0].toUpperCase()+view.slice(1)} <span>/</span> <b>${view==='overview'?'Global view':'Operations'}</b>`;window.scrollTo({top:0,behavior:'smooth'})}
document.addEventListener('click',e=>{const control=e.target.closest('[data-view]');if(control){e.preventDefault();navigate(control.dataset.view)}const site=e.target.closest('.site-drill');if(site){navigate('sites');$('#site-search').value=site.dataset.site;renderSites()}const alert=e.target.closest('[data-alert]');if(alert)selectAlert(+alert.dataset.alert)});
['site-search','site-filter'].forEach(x=>$('#'+x).addEventListener('input',renderSites));['device-search','device-filter'].forEach(x=>$('#'+x).addEventListener('input',renderDevices));['client-search','client-filter'].forEach(x=>$('#'+x).addEventListener('input',renderClients));
function demoAnswer(question) {
  const q = question.toLowerCase();
  if (q.includes('london') || q.includes('experience')) return `<div><div class="answer-title">London Office experience is below baseline</div><p>Experience is <b>82/100</b>, compared with a 91 global average. I correlated this with 27 roaming failures across six access points in the last hour.</p><ul class="answer-list"><li>Primary factor: high 5 GHz channel utilization (78%)</li><li>Impacted clients: 27 of 892 (3.0%)</li><li>Suggested next step: enable band steering and rebalance channels</li></ul></div>`;
  if (q.includes('alert') || q.includes('incident')) return `<div><div class="answer-title">${alerts.length} active alerts need attention</div><ul class="answer-list"><li><b>Critical:</b> London roaming failures — 8 minutes old</li><li><b>High:</b> Singapore WAN latency — 42 ms above baseline</li><li><b>High:</b> Singapore gateway CPU — sustained at 84%</li><li><b>Low:</b> Approved firmware available for 18 APs</li></ul><p>I recommend investigating the London issue first because it has the highest client impact.</p></div>`;
  if (q.includes('wan') || q.includes('link') || q.includes('latency')) return `<div><div class="answer-title">Singapore primary WAN link needs attention</div><p>Median latency is <b>42 ms</b>, which is 42 ms above its expected baseline. The backup tunnel is healthy at 18 ms.</p><ul class="answer-list"><li>Traffic at risk: real-time collaboration and voice</li><li>Recommended action: shift latency-sensitive traffic to backup</li><li>Confidence: high (based on simulated packet and path telemetry)</li></ul></div>`;
  if (q.includes('remediation') || q.includes('fix') || q.includes('plan')) return `<div><div class="answer-title">Recommended remediation plan</div><ul class="answer-list"><li><b>Now:</b> Route voice and video from Singapore to the backup WAN link.</li><li><b>Next:</b> Apply channel optimization to the six affected London access points.</li><li><b>Tonight:</b> Schedule the approved access point firmware update.</li></ul><p>Expected result: London experience should return above 90/100 and WAN latency should fall below 20 ms.</p></div>`;
  if (q.includes('client') || q.includes('health')) return `<div><div class="answer-title">Client health summary</div><p>There are <b>${totalClients.toLocaleString()} connected clients</b>: 75% wireless and 25% wired. Wi-Fi experience is 94/100 and wired experience is 88/100.</p><ul class="answer-list"><li>Healthy clients: 96.8%</li><li>Clients with degraded experience: 3.0%</li><li>Offline client change: within normal range</li></ul></div>`;
  return `<div><div class="answer-title">Network summary</div><p>Global health is <b>98.7%</b>. I’m tracking ${totalClients.toLocaleString()} connected clients across 17 sites. The main item to watch is London roaming performance; no sites are offline.</p><p>Try asking about London, alerts, WAN latency, remediation, or client health.</p></div>`;
}
function ask(q){q=q||$('#assist-question').value; if(!q.trim())return;const history=$('#assist-history');history.insertAdjacentHTML('beforeend',`<div class="user-message">${q}</div><div class="bot-message typing" id="assistant-typing"><span>✦</span><p>Analyzing network telemetry…</p></div>`);$('#assist-question').value='';history.scrollTop=9999;setTimeout(()=>{ $('#assistant-typing')?.remove();history.insertAdjacentHTML('beforeend',`<div class="bot-message"><span>✦</span><div>${demoAnswer(q)}<p class="eyebrow" style="margin-top:11px">SIMULATED RESPONSE · LIVE API READY</p></div></div>`);history.scrollTop=9999;},650)}
$('#ask-assist').addEventListener('click',()=>ask());$('#assist-question').addEventListener('keydown',e=>{if(e.key==='Enter')ask()});document.querySelectorAll('.quick-prompts button').forEach(x=>x.addEventListener('click',()=>ask(x.textContent)));
function toast(msg){const x=$('#toast');x.textContent=msg;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2400)}
$('#report').addEventListener('click',()=>toast('Live operations report prepared'));$('#global-search').addEventListener('click',()=>{navigate('inventory');$('#device-search').focus()});$('#add-site').addEventListener('click',()=>$('#modal').classList.add('open'));$('#adopt-device').addEventListener('click',()=>toast('Device adoption workflow started'));$('#modal-close').addEventListener('click',()=>$('#modal').classList.remove('open'));$('#modal-form').addEventListener('submit',e=>{e.preventDefault();toast('Site added to staging');$('#modal').classList.remove('open')});$('#resolve-all').addEventListener('click',()=>{alerts=alerts.filter(x=>x.level!=='low');renderAlerts();toast('Low priority alert resolved')});
function live(){totalClients+=Math.floor(Math.random()*18)-6;$('#clients').textContent=totalClients.toLocaleString();$('#wireless').textContent=Math.round(totalClients*.75).toLocaleString();$('#wired').textContent=Math.round(totalClients*.25).toLocaleString();$('#update-label').textContent='Updated '+new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});$('#clock').textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'})}setInterval(live,3500);live();renderSites();renderDevices();renderClients();renderOverview();renderWan();renderAlerts();

let authMode = 'signup';
function setUser(user) {
  if (!user) return;
  $('#welcome-title').textContent = `Good morning, ${user.name.split(' ')[0]}.`;
  $('#sidebar-name').textContent = user.name;
  $('#sidebar-role').textContent = 'Network Admin';
  $('#user-initials').textContent = user.name.split(' ').map(part => part[0]).join('').slice(0, 2).toUpperCase();
  $('#auth-gate').classList.add('hidden');
}
function updateAuthMode() {
  const signingIn = authMode === 'login';
  $('#auth-title').textContent = signingIn ? 'Welcome back' : 'Create your account';
  $('#auth-copy').textContent = signingIn ? 'Sign in to access your network operations console.' : 'Start monitoring your network in minutes.';
  $('.name-field').style.display = signingIn ? 'none' : 'grid';
  $('#auth-name').required = !signingIn;
  $('#auth-password').autocomplete = signingIn ? 'current-password' : 'new-password';
  $('#auth-submit').textContent = signingIn ? 'Sign in' : 'Create account';
  $('#auth-switch').innerHTML = signingIn ? 'New to Vanta Cloud? <button>Create an account</button>' : 'Already have an account? <button>Sign in</button>';
  $('#auth-switch button').addEventListener('click', () => { authMode = signingIn ? 'signup' : 'login'; $('#auth-error').textContent = ''; updateAuthMode(); });
}
$('#auth-form').addEventListener('submit', async event => {
  event.preventDefault();
  const error = $('#auth-error'); error.textContent = '';
  const submit = $('#auth-submit'); submit.disabled = true; submit.textContent = 'Please wait…';
  try {
    const response = await fetch(`/api/${authMode}`, { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({name:$('#auth-name').value, email:$('#auth-email').value, password:$('#auth-password').value}) });
    const data = await response.json();
    if (!response.ok) throw new Error(data.error || 'Unable to sign in.');
    setUser(data.user); toast(`Welcome, ${data.user.name.split(' ')[0]}`);
  } catch (err) { error.textContent = err.message; }
  finally { submit.disabled = false; submit.textContent = authMode === 'login' ? 'Sign in' : 'Create account'; }
});
$('#logout').addEventListener('click', async () => { await fetch('/api/logout',{method:'POST'}); $('#auth-form').reset(); authMode='login'; updateAuthMode(); $('#auth-gate').classList.remove('hidden'); $('#welcome-title').textContent='Welcome to Vanta Cloud.'; $('#sidebar-name').textContent='Guest user'; $('#sidebar-role').textContent='Sign in to continue'; $('#user-initials').textContent='--'; });
fetch('/api/me').then(response => response.json()).then(data => { if (data.user) setUser(data.user); else updateAuthMode(); }).catch(() => updateAuthMode());
